#############################################################################
# Makefile for building: newCommissioner
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sun Oct 30 17:01:36 2016
# Project:  newCommissioner.pro
# Template: app
# Command: /opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/qmake -o Makefile newCommissioner.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../Qt-4.8.2/mkspecs/linux-g++-64 -I. -I../../../Qt-4.8.2/include/QtCore -I../../../Qt-4.8.2/include/QtGui -I../../../Qt-4.8.2/include -I/opt/xdaq/include -I$(QTROOTSYSDIR)/include -I$(ROOTSYS)/include -I.moc -I.ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/lib -L/opt/xdaq/lib/ -L$(QTROOTSYSDIR)/lib -lGQt -lQtRootGui -L/opt/cmssw/shifter/avartak/qtRoot/root/lib -lGui -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -lTable -lQtGui -L/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/lib -L/usr/X11R6/lib64 -lQtCore -lclntsh -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		Debug.cpp \
		DbConnection.cpp \
		TreeBuilder.cpp \
		TreeViewerRunInfo.cpp \
		FedView.cpp \
		FedGraphicsView.cpp \
		FedGraphicsScene.cpp \
		Chip.cpp \
		TkView.cpp \
		frmstartup.cpp \
		frmtreeviewer.cpp \
		frmruninfo.cpp \
		frmdetails.cpp \
		frmsource.cpp \
		frmtkmap.cpp \
		frmfedmap.cpp \
		cmssw/SiStripKey.cc \
		cmssw/SiStripFecKey.cc \
		cmssw/SiStripFedKey.cc .moc/moc_QConnectedTabWidget.cpp \
		.moc/moc_CustomTQtWidget.cpp \
		.moc/moc_FedGraphicsView.cpp \
		.moc/moc_FedGraphicsScene.cpp \
		.moc/moc_TkView.cpp \
		.moc/moc_frmcommissioner.cpp \
		.moc/moc_frmstartup.cpp \
		.moc/moc_frmtreeviewer.cpp \
		.moc/moc_frmreferencechooser.cpp \
		.moc/moc_frmruninfo.cpp \
		.moc/moc_frmdetails.cpp \
		.moc/moc_frmdbtag.cpp \
		.moc/moc_frmtrends.cpp \
		.moc/moc_frmsource.cpp \
		.moc/moc_frmtkmap.cpp \
		.moc/moc_frmfedmap.cpp \
		.moc/moc_frmterminal.cpp
OBJECTS       = .obj/main.o \
		.obj/Debug.o \
		.obj/DbConnection.o \
		.obj/TreeBuilder.o \
		.obj/TreeViewerRunInfo.o \
		.obj/FedView.o \
		.obj/FedGraphicsView.o \
		.obj/FedGraphicsScene.o \
		.obj/Chip.o \
		.obj/TkView.o \
		.obj/frmstartup.o \
		.obj/frmtreeviewer.o \
		.obj/frmruninfo.o \
		.obj/frmdetails.o \
		.obj/frmsource.o \
		.obj/frmtkmap.o \
		.obj/frmfedmap.o \
		.obj/SiStripKey.o \
		.obj/SiStripFecKey.o \
		.obj/SiStripFedKey.o \
		.obj/moc_QConnectedTabWidget.o \
		.obj/moc_CustomTQtWidget.o \
		.obj/moc_FedGraphicsView.o \
		.obj/moc_FedGraphicsScene.o \
		.obj/moc_TkView.o \
		.obj/moc_frmcommissioner.o \
		.obj/moc_frmstartup.o \
		.obj/moc_frmtreeviewer.o \
		.obj/moc_frmreferencechooser.o \
		.obj/moc_frmruninfo.o \
		.obj/moc_frmdetails.o \
		.obj/moc_frmdbtag.o \
		.obj/moc_frmtrends.o \
		.obj/moc_frmsource.o \
		.obj/moc_frmtkmap.o \
		.obj/moc_frmfedmap.o \
		.obj/moc_frmterminal.o
DIST          = ../../../Qt-4.8.2/mkspecs/common/unix.conf \
		../../../Qt-4.8.2/mkspecs/common/linux.conf \
		../../../Qt-4.8.2/mkspecs/common/gcc-base.conf \
		../../../Qt-4.8.2/mkspecs/common/gcc-base-unix.conf \
		../../../Qt-4.8.2/mkspecs/common/g++-base.conf \
		../../../Qt-4.8.2/mkspecs/common/g++-unix.conf \
		../../../Qt-4.8.2/mkspecs/qconfig.pri \
		../../../Qt-4.8.2/mkspecs/modules/qt_webkit_version.pri \
		../../../Qt-4.8.2/mkspecs/features/qt_functions.prf \
		../../../Qt-4.8.2/mkspecs/features/qt_config.prf \
		../../../Qt-4.8.2/mkspecs/features/exclusive_builds.prf \
		../../../Qt-4.8.2/mkspecs/features/default_pre.prf \
		../../../root/include/rootlibs.pri \
		../../../root/include/rootcintrule.pri \
		../../../root/include/rootcint.pri \
		../../../Qt-4.8.2/mkspecs/features/release.prf \
		../../../Qt-4.8.2/mkspecs/features/default_post.prf \
		../../../Qt-4.8.2/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt-4.8.2/mkspecs/features/warn_on.prf \
		../../../Qt-4.8.2/mkspecs/features/qt.prf \
		../../../Qt-4.8.2/mkspecs/features/unix/thread.prf \
		../../../Qt-4.8.2/mkspecs/features/moc.prf \
		../../../Qt-4.8.2/mkspecs/features/resources.prf \
		../../../Qt-4.8.2/mkspecs/features/uic.prf \
		../../../Qt-4.8.2/mkspecs/features/yacc.prf \
		../../../Qt-4.8.2/mkspecs/features/lex.prf \
		newCommissioner.pro
QMAKE_TARGET  = newCommissioner
DESTDIR       = 
TARGET        = newCommissioner

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .ui/ui_frmcommissioner.h .ui/ui_frmstartup.h .ui/ui_frmtreeviewer.h .ui/ui_frmreferencechooser.h .ui/ui_frmruninfo.h .ui/ui_frmfedmap.h .ui/ui_frmdetails.h .ui/ui_frmdbtag.h .ui/ui_frmsource.h .ui/ui_frmtrends.h .ui/ui_frmterminal.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: newCommissioner.pro  ../../../Qt-4.8.2/mkspecs/linux-g++-64/qmake.conf ../../../Qt-4.8.2/mkspecs/common/unix.conf \
		../../../Qt-4.8.2/mkspecs/common/linux.conf \
		../../../Qt-4.8.2/mkspecs/common/gcc-base.conf \
		../../../Qt-4.8.2/mkspecs/common/gcc-base-unix.conf \
		../../../Qt-4.8.2/mkspecs/common/g++-base.conf \
		../../../Qt-4.8.2/mkspecs/common/g++-unix.conf \
		../../../Qt-4.8.2/mkspecs/qconfig.pri \
		../../../Qt-4.8.2/mkspecs/modules/qt_webkit_version.pri \
		../../../Qt-4.8.2/mkspecs/features/qt_functions.prf \
		../../../Qt-4.8.2/mkspecs/features/qt_config.prf \
		../../../Qt-4.8.2/mkspecs/features/exclusive_builds.prf \
		../../../Qt-4.8.2/mkspecs/features/default_pre.prf \
		../../../root/include/rootlibs.pri \
		../../../root/include/rootcintrule.pri \
		../../../root/include/rootcint.pri \
		../../../Qt-4.8.2/mkspecs/features/release.prf \
		../../../Qt-4.8.2/mkspecs/features/default_post.prf \
		../../../Qt-4.8.2/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt-4.8.2/mkspecs/features/warn_on.prf \
		../../../Qt-4.8.2/mkspecs/features/qt.prf \
		../../../Qt-4.8.2/mkspecs/features/unix/thread.prf \
		../../../Qt-4.8.2/mkspecs/features/moc.prf \
		../../../Qt-4.8.2/mkspecs/features/resources.prf \
		../../../Qt-4.8.2/mkspecs/features/uic.prf \
		../../../Qt-4.8.2/mkspecs/features/yacc.prf \
		../../../Qt-4.8.2/mkspecs/features/lex.prf \
		/opt/cmssw/shifter/avartak/qtRoot/root/lib/libGQt.prl \
		/opt/cmssw/shifter/avartak/qtRoot/root/lib/libQtRootGui.prl \
		/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/lib/libQtGui.prl \
		/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/lib/libQtCore.prl
	$(QMAKE) -o Makefile newCommissioner.pro
../../../Qt-4.8.2/mkspecs/common/unix.conf:
../../../Qt-4.8.2/mkspecs/common/linux.conf:
../../../Qt-4.8.2/mkspecs/common/gcc-base.conf:
../../../Qt-4.8.2/mkspecs/common/gcc-base-unix.conf:
../../../Qt-4.8.2/mkspecs/common/g++-base.conf:
../../../Qt-4.8.2/mkspecs/common/g++-unix.conf:
../../../Qt-4.8.2/mkspecs/qconfig.pri:
../../../Qt-4.8.2/mkspecs/modules/qt_webkit_version.pri:
../../../Qt-4.8.2/mkspecs/features/qt_functions.prf:
../../../Qt-4.8.2/mkspecs/features/qt_config.prf:
../../../Qt-4.8.2/mkspecs/features/exclusive_builds.prf:
../../../Qt-4.8.2/mkspecs/features/default_pre.prf:
../../../root/include/rootlibs.pri:
../../../root/include/rootcintrule.pri:
../../../root/include/rootcint.pri:
../../../Qt-4.8.2/mkspecs/features/release.prf:
../../../Qt-4.8.2/mkspecs/features/default_post.prf:
../../../Qt-4.8.2/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Qt-4.8.2/mkspecs/features/warn_on.prf:
../../../Qt-4.8.2/mkspecs/features/qt.prf:
../../../Qt-4.8.2/mkspecs/features/unix/thread.prf:
../../../Qt-4.8.2/mkspecs/features/moc.prf:
../../../Qt-4.8.2/mkspecs/features/resources.prf:
../../../Qt-4.8.2/mkspecs/features/uic.prf:
../../../Qt-4.8.2/mkspecs/features/yacc.prf:
../../../Qt-4.8.2/mkspecs/features/lex.prf:
/opt/cmssw/shifter/avartak/qtRoot/root/lib/libGQt.prl:
/opt/cmssw/shifter/avartak/qtRoot/root/lib/libQtRootGui.prl:
/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/lib/libQtGui.prl:
/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile newCommissioner.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/newCommissioner1.0.0 || $(MKDIR) .obj/newCommissioner1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/newCommissioner1.0.0/ && $(COPY_FILE) --parents Debug.h DbConnection.h QConnectedTabWidget.h CustomTQtWidget.h BaseTypes.h TreeBuilder.h TreeViewerRunInfo.h FedView.h FedGraphicsView.h FedGraphicsScene.h TkMapGlobals.h Chip.h TkView.h frmcommissioner.h frmstartup.h frmtreeviewer.h frmreferencechooser.h frmruninfo.h frmdetails.h frmdbtag.h frmtrends.h frmsource.h frmtkmap.h frmfedmap.h frmterminal.h cmssw/SiStripFecKey.h cmssw/SiStripFedKey.h .obj/newCommissioner1.0.0/ && $(COPY_FILE) --parents main.cpp Debug.cpp DbConnection.cpp TreeBuilder.cpp TreeViewerRunInfo.cpp FedView.cpp FedGraphicsView.cpp FedGraphicsScene.cpp Chip.cpp TkView.cpp frmstartup.cpp frmtreeviewer.cpp frmruninfo.cpp frmdetails.cpp frmsource.cpp frmtkmap.cpp frmfedmap.cpp cmssw/SiStripKey.cc cmssw/SiStripFecKey.cc cmssw/SiStripFedKey.cc .obj/newCommissioner1.0.0/ && $(COPY_FILE) --parents uifiles/frmcommissioner.ui uifiles/frmstartup.ui uifiles/frmtreeviewer.ui uifiles/frmreferencechooser.ui uifiles/frmruninfo.ui uifiles/frmfedmap.ui uifiles/frmdetails.ui uifiles/frmdbtag.ui uifiles/frmsource.ui uifiles/frmtrends.ui uifiles/frmterminal.ui .obj/newCommissioner1.0.0/ && (cd `dirname .obj/newCommissioner1.0.0` && $(TAR) newCommissioner1.0.0.tar newCommissioner1.0.0 && $(COMPRESS) newCommissioner1.0.0.tar) && $(MOVE) `dirname .obj/newCommissioner1.0.0`/newCommissioner1.0.0.tar.gz . && $(DEL_FILE) -r .obj/newCommissioner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_QConnectedTabWidget.cpp .moc/moc_CustomTQtWidget.cpp .moc/moc_FedGraphicsView.cpp .moc/moc_FedGraphicsScene.cpp .moc/moc_TkView.cpp .moc/moc_frmcommissioner.cpp .moc/moc_frmstartup.cpp .moc/moc_frmtreeviewer.cpp .moc/moc_frmreferencechooser.cpp .moc/moc_frmruninfo.cpp .moc/moc_frmdetails.cpp .moc/moc_frmdbtag.cpp .moc/moc_frmtrends.cpp .moc/moc_frmsource.cpp .moc/moc_frmtkmap.cpp .moc/moc_frmfedmap.cpp .moc/moc_frmterminal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_QConnectedTabWidget.cpp .moc/moc_CustomTQtWidget.cpp .moc/moc_FedGraphicsView.cpp .moc/moc_FedGraphicsScene.cpp .moc/moc_TkView.cpp .moc/moc_frmcommissioner.cpp .moc/moc_frmstartup.cpp .moc/moc_frmtreeviewer.cpp .moc/moc_frmreferencechooser.cpp .moc/moc_frmruninfo.cpp .moc/moc_frmdetails.cpp .moc/moc_frmdbtag.cpp .moc/moc_frmtrends.cpp .moc/moc_frmsource.cpp .moc/moc_frmtkmap.cpp .moc/moc_frmfedmap.cpp .moc/moc_frmterminal.cpp
.moc/moc_QConnectedTabWidget.cpp: QConnectedTabWidget.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) QConnectedTabWidget.h -o .moc/moc_QConnectedTabWidget.cpp

.moc/moc_CustomTQtWidget.cpp: $(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		CustomTQtWidget.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) CustomTQtWidget.h -o .moc/moc_CustomTQtWidget.cpp

.moc/moc_FedGraphicsView.cpp: FedGraphicsView.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) FedGraphicsView.h -o .moc/moc_FedGraphicsView.cpp

.moc/moc_FedGraphicsScene.cpp: FedGraphicsScene.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) FedGraphicsScene.h -o .moc/moc_FedGraphicsScene.cpp

.moc/moc_TkView.cpp: TkMapGlobals.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArray.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		TkView.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) TkView.h -o .moc/moc_TkView.cpp

.moc/moc_frmcommissioner.cpp: QConnectedTabWidget.h \
		frmstartup.h \
		.ui/ui_frmstartup.h \
		.ui/ui_frmcommissioner.h \
		frmcommissioner.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmcommissioner.h -o .moc/moc_frmcommissioner.cpp

.moc/moc_frmstartup.cpp: QConnectedTabWidget.h \
		.ui/ui_frmstartup.h \
		frmstartup.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmstartup.h -o .moc/moc_frmstartup.cpp

.moc/moc_frmtreeviewer.cpp: $(QTROOTSYSDIR)/include/TH1F.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		.ui/ui_frmtreeviewer.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TAttText.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		QConnectedTabWidget.h \
		TreeViewerRunInfo.h \
		frmtreeviewer.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmtreeviewer.h -o .moc/moc_frmtreeviewer.cpp

.moc/moc_frmreferencechooser.cpp: .ui/ui_frmreferencechooser.h \
		frmreferencechooser.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmreferencechooser.h -o .moc/moc_frmreferencechooser.cpp

.moc/moc_frmruninfo.cpp: .ui/ui_frmruninfo.h \
		QConnectedTabWidget.h \
		frmruninfo.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmruninfo.h -o .moc/moc_frmruninfo.cpp

.moc/moc_frmdetails.cpp: .ui/ui_frmdetails.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		TreeViewerRunInfo.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TH1F.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		frmdetails.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmdetails.h -o .moc/moc_frmdetails.cpp

.moc/moc_frmdbtag.cpp: Debug.h \
		DbConnection.h \
		frmdbtag.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmdbtag.h -o .moc/moc_frmdbtag.cpp

.moc/moc_frmtrends.cpp: .ui/ui_frmtrends.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TGraph.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArray.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		../../../root/include/TAttAxis.h \
		$(QTROOTSYSDIR)/include/TMath.h \
		../../../root/include/TError.h \
		../../../root/include/TAxis.h \
		../../../root/include/TArrayD.h \
		frmtrends.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmtrends.h -o .moc/moc_frmtrends.cpp

.moc/moc_frmsource.cpp: .ui/ui_frmsource.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		frmsource.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmsource.h -o .moc/moc_frmsource.cpp

.moc/moc_frmtkmap.cpp: QConnectedTabWidget.h \
		Chip.h \
		TkMapGlobals.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArray.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		$(QTROOTSYSDIR)/include/TText.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TDataType.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		frmtkmap.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmtkmap.h -o .moc/moc_frmtkmap.cpp

.moc/moc_frmfedmap.cpp: .ui/ui_frmfedmap.h \
		FedGraphicsView.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		FedView.h \
		FedGraphicsScene.h \
		frmfedmap.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmfedmap.h -o .moc/moc_frmfedmap.cpp

.moc/moc_frmterminal.cpp: .ui/ui_frmterminal.h \
		QConnectedTabWidget.h \
		Debug.h \
		frmterminal.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/moc $(DEFINES) $(INCPATH) frmterminal.h -o .moc/moc_frmterminal.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: .ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .ui/ui_frmcommissioner.h .ui/ui_frmstartup.h .ui/ui_frmtreeviewer.h .ui/ui_frmreferencechooser.h .ui/ui_frmruninfo.h .ui/ui_frmfedmap.h .ui/ui_frmdetails.h .ui/ui_frmdbtag.h .ui/ui_frmsource.h .ui/ui_frmtrends.h .ui/ui_frmterminal.h
compiler_uic_clean:
	-$(DEL_FILE) .ui/ui_frmcommissioner.h .ui/ui_frmstartup.h .ui/ui_frmtreeviewer.h .ui/ui_frmreferencechooser.h .ui/ui_frmruninfo.h .ui/ui_frmfedmap.h .ui/ui_frmdetails.h .ui/ui_frmdbtag.h .ui/ui_frmsource.h .ui/ui_frmtrends.h .ui/ui_frmterminal.h
.ui/ui_frmcommissioner.h: uifiles/frmcommissioner.ui
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmcommissioner.ui -o .ui/ui_frmcommissioner.h

.ui/ui_frmstartup.h: uifiles/frmstartup.ui \
		QConnectedTabWidget.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmstartup.ui -o .ui/ui_frmstartup.h

.ui/ui_frmtreeviewer.h: uifiles/frmtreeviewer.ui \
		CustomTQtWidget.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmtreeviewer.ui -o .ui/ui_frmtreeviewer.h

.ui/ui_frmreferencechooser.h: uifiles/frmreferencechooser.ui
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmreferencechooser.ui -o .ui/ui_frmreferencechooser.h

.ui/ui_frmruninfo.h: uifiles/frmruninfo.ui \
		QConnectedTabWidget.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmruninfo.ui -o .ui/ui_frmruninfo.h

.ui/ui_frmfedmap.h: uifiles/frmfedmap.ui \
		QConnectedTabWidget.h \
		FedGraphicsView.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmfedmap.ui -o .ui/ui_frmfedmap.h

.ui/ui_frmdetails.h: uifiles/frmdetails.ui \
		QConnectedTabWidget.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmdetails.ui -o .ui/ui_frmdetails.h

.ui/ui_frmdbtag.h: uifiles/frmdbtag.ui
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmdbtag.ui -o .ui/ui_frmdbtag.h

.ui/ui_frmsource.h: uifiles/frmsource.ui \
		CustomTQtWidget.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmsource.ui -o .ui/ui_frmsource.h

.ui/ui_frmtrends.h: uifiles/frmtrends.ui \
		CustomTQtWidget.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmtrends.ui -o .ui/ui_frmtrends.h

.ui/ui_frmterminal.h: uifiles/frmterminal.ui \
		QConnectedTabWidget.h
	/opt/cmssw/shifter/avartak/qtRoot/Qt-4.8.2/bin/uic uifiles/frmterminal.ui -o .ui/ui_frmterminal.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

.obj/main.o: main.cpp Debug.h \
		DbConnection.h \
		frmcommissioner.h \
		QConnectedTabWidget.h \
		frmstartup.h \
		.ui/ui_frmstartup.h \
		.ui/ui_frmcommissioner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/Debug.o: Debug.cpp Debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Debug.o Debug.cpp

.obj/DbConnection.o: DbConnection.cpp DbConnection.h \
		Debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/DbConnection.o DbConnection.cpp

.obj/TreeBuilder.o: TreeBuilder.cpp TreeBuilder.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		BaseTypes.h \
		Debug.h \
		DbConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/TreeBuilder.o TreeBuilder.cpp

.obj/TreeViewerRunInfo.o: TreeViewerRunInfo.cpp TreeViewerRunInfo.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TList.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TH1F.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TEventList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/TreeViewerRunInfo.o TreeViewerRunInfo.cpp

.obj/FedView.o: FedView.cpp FedView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/FedView.o FedView.cpp

.obj/FedGraphicsView.o: FedGraphicsView.cpp FedGraphicsView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/FedGraphicsView.o FedGraphicsView.cpp

.obj/FedGraphicsScene.o: FedGraphicsScene.cpp FedGraphicsScene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/FedGraphicsScene.o FedGraphicsScene.cpp

.obj/Chip.o: Chip.cpp Chip.h \
		TkMapGlobals.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArray.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		$(QTROOTSYSDIR)/include/TText.h \
		frmsource.h \
		.ui/ui_frmsource.h \
		CustomTQtWidget.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Chip.o Chip.cpp

.obj/TkView.o: TkView.cpp TkView.h \
		TkMapGlobals.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArray.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/TkView.o TkView.cpp

.obj/frmstartup.o: frmstartup.cpp frmstartup.h \
		QConnectedTabWidget.h \
		.ui/ui_frmstartup.h \
		frmtreeviewer.h \
		$(QTROOTSYSDIR)/include/TH1F.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		.ui/ui_frmtreeviewer.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TAttText.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		TreeViewerRunInfo.h \
		frmterminal.h \
		.ui/ui_frmterminal.h \
		Debug.h \
		TreeBuilder.h \
		BaseTypes.h \
		DbConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmstartup.o frmstartup.cpp

.obj/frmtreeviewer.o: frmtreeviewer.cpp Debug.h \
		cmssw/SiStripFecKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripKey.h \
		cmssw/SiStripFedKey.h \
		FedView.h \
		TreeBuilder.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		BaseTypes.h \
		frmtreeviewer.h \
		$(QTROOTSYSDIR)/include/TH1F.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		.ui/ui_frmtreeviewer.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TAttText.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		QConnectedTabWidget.h \
		TreeViewerRunInfo.h \
		frmreferencechooser.h \
		.ui/ui_frmreferencechooser.h \
		frmruninfo.h \
		.ui/ui_frmruninfo.h \
		frmdetails.h \
		.ui/ui_frmdetails.h \
		frmtkmap.h \
		Chip.h \
		TkMapGlobals.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		$(QTROOTSYSDIR)/include/TText.h \
		frmfedmap.h \
		.ui/ui_frmfedmap.h \
		FedGraphicsView.h \
		FedGraphicsScene.h \
		$(QTROOTSYSDIR)/include/TKey.h \
		$(QTROOTSYSDIR)/include/TEnv.h \
		$(QTROOTSYSDIR)/include/TChain.h \
		$(QTROOTSYSDIR)/include/TChainElement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmtreeviewer.o frmtreeviewer.cpp

.obj/frmruninfo.o: frmruninfo.cpp frmruninfo.h \
		.ui/ui_frmruninfo.h \
		QConnectedTabWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmruninfo.o frmruninfo.cpp

.obj/frmdetails.o: frmdetails.cpp frmdetails.h \
		.ui/ui_frmdetails.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		TreeViewerRunInfo.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TH1F.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		frmtrends.h \
		.ui/ui_frmtrends.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TAttText.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		$(QTROOTSYSDIR)/include/TGraph.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		$(QTROOTSYSDIR)/include/TMath.h \
		../../../root/include/TError.h \
		frmsource.h \
		.ui/ui_frmsource.h \
		Debug.h \
		cmssw/SiStripFedKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripKey.h \
		cmssw/SiStripFecKey.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmdetails.o frmdetails.cpp

.obj/frmsource.o: frmsource.cpp Debug.h \
		frmsource.h \
		.ui/ui_frmsource.h \
		CustomTQtWidget.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TChain.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TDataType.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TChainElement.h \
		$(QTROOTSYSDIR)/include/TKey.h \
		../../../root/include/TH1.h \
		../../../root/include/TAxis.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TArrayC.h \
		../../../root/include/TArrayS.h \
		../../../root/include/TArrayF.h \
		../../../root/include/Foption.h \
		../../../root/include/TVectorFfwd.h \
		../../../root/include/TVectorDfwd.h \
		../../../root/include/TFitResultPtr.h \
		cmssw/SiStripFedKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripKey.h \
		cmssw/SiStripFecKey.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmsource.o frmsource.cpp

.obj/frmtkmap.o: frmtkmap.cpp frmtkmap.h \
		QConnectedTabWidget.h \
		Chip.h \
		TkMapGlobals.h \
		$(QTROOTSYSDIR)/include/TColor.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TArray.h \
		$(QTROOTSYSDIR)/include/TROOT.h \
		../../../root/include/TDirectory.h \
		../../../root/include/TList.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TDatime.h \
		../../../root/include/TUUID.h \
		$(QTROOTSYSDIR)/include/TStyle.h \
		../../../root/include/TAttAxis.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TAttText.h \
		../../../root/include/TAttMarker.h \
		$(QTROOTSYSDIR)/include/TQtWidget.h \
		../../../root/include/TCanvas.h \
		../../../root/include/TPad.h \
		../../../root/include/TVirtualPad.h \
		../../../root/include/TAttPad.h \
		../../../root/include/TVirtualX.h \
		../../../root/include/GuiTypes.h \
		../../../root/include/Buttons.h \
		../../../root/include/TQObject.h \
		../../../root/include/TQClass.h \
		../../../root/include/TClass.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TObjString.h \
		../../../root/include/TAttCanvas.h \
		../../../root/include/TCanvasImp.h \
		../../../root/include/TQtCanvasPainter.h \
		$(QTROOTSYSDIR)/include/TText.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TDataType.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TVirtualTreePlayer.h \
		$(QTROOTSYSDIR)/include/TEventList.h \
		cmssw/SiStripFecKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripKey.h \
		cmssw/SiStripFedKey.h \
		TkView.h \
		$(QTROOTSYSDIR)/include/TFile.h \
		../../../root/include/TDirectoryFile.h \
		../../../root/include/TMap.h \
		../../../root/include/THashTable.h \
		../../../root/include/TUrl.h \
		$(QTROOTSYSDIR)/include/TLeaf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmtkmap.o frmtkmap.cpp

.obj/frmfedmap.o: frmfedmap.cpp frmfedmap.h \
		.ui/ui_frmfedmap.h \
		FedGraphicsView.h \
		QConnectedTabWidget.h \
		$(QTROOTSYSDIR)/include/TTree.h \
		../../../root/include/TBranch.h \
		../../../root/include/TNamed.h \
		../../../root/include/TObject.h \
		../../../root/include/Rtypes.h \
		../../../root/include/RConfig.h \
		../../../root/include/RVersion.h \
		../../../root/include/DllImport.h \
		../../../root/include/Rtypeinfo.h \
		$(QTROOTSYSDIR)/include/snprintf.h \
		$(QTROOTSYSDIR)/include/strlcpy.h \
		../../../root/include/TGenericClassInfo.h \
		../../../root/include/TSchemaHelper.h \
		../../../root/include/TStorage.h \
		../../../root/include/TVersionCheck.h \
		../../../root/include/Riosfwd.h \
		../../../root/include/TBuffer.h \
		../../../root/include/TString.h \
		../../../root/include/TMathBase.h \
		../../../root/include/TObjArray.h \
		../../../root/include/TSeqCollection.h \
		../../../root/include/TCollection.h \
		../../../root/include/TIterator.h \
		../../../root/include/TAttFill.h \
		../../../root/include/TDataType.h \
		../../../root/include/TDictionary.h \
		../../../root/include/Property.h \
		../../../root/include/TAttLine.h \
		../../../root/include/TAttMarker.h \
		../../../root/include/TArrayD.h \
		../../../root/include/TArray.h \
		../../../root/include/TArrayI.h \
		../../../root/include/TClass.h \
		../../../root/include/TObjString.h \
		../../../root/include/TVirtualTreePlayer.h \
		FedView.h \
		FedGraphicsScene.h \
		frmterminal.h \
		.ui/ui_frmterminal.h \
		Debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frmfedmap.o frmfedmap.cpp

.obj/SiStripKey.o: cmssw/SiStripKey.cc cmssw/SiStripKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripEnumsAndStrings.h \
		cmssw/SiStripConstants.h \
		cmssw/ConstantsForCablingSource.h \
		cmssw/ConstantsForCommissioningAnalysis.h \
		cmssw/ConstantsForDqm.h \
		cmssw/ConstantsForHardwareSystems.h \
		cmssw/FEDNumbering.h \
		cmssw/ConstantsForHistoType.h \
		cmssw/ConstantsForKeyType.h \
		cmssw/ConstantsForLogger.h \
		cmssw/ConstantsForMonitorable.h \
		cmssw/ConstantsForPresentation.h \
		cmssw/ConstantsForRunType.h \
		cmssw/ConstantsForView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/SiStripKey.o cmssw/SiStripKey.cc

.obj/SiStripFecKey.o: cmssw/SiStripFecKey.cc cmssw/SiStripFecKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripKey.h \
		cmssw/ConstantsForHardwareSystems.h \
		cmssw/FEDNumbering.h \
		cmssw/ConstantsForDqm.h \
		cmssw/ConstantsForView.h \
		cmssw/SiStripEnumsAndStrings.h \
		cmssw/SiStripConstants.h \
		cmssw/ConstantsForCablingSource.h \
		cmssw/ConstantsForCommissioningAnalysis.h \
		cmssw/ConstantsForHistoType.h \
		cmssw/ConstantsForKeyType.h \
		cmssw/ConstantsForLogger.h \
		cmssw/ConstantsForMonitorable.h \
		cmssw/ConstantsForPresentation.h \
		cmssw/ConstantsForRunType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/SiStripFecKey.o cmssw/SiStripFecKey.cc

.obj/SiStripFedKey.o: cmssw/SiStripFedKey.cc cmssw/SiStripFedKey.h \
		cmssw/ConstantsForGranularity.h \
		cmssw/Constants.h \
		cmssw/SiStripKey.h \
		cmssw/ConstantsForHardwareSystems.h \
		cmssw/FEDNumbering.h \
		cmssw/ConstantsForDqm.h \
		cmssw/ConstantsForView.h \
		cmssw/SiStripEnumsAndStrings.h \
		cmssw/SiStripConstants.h \
		cmssw/ConstantsForCablingSource.h \
		cmssw/ConstantsForCommissioningAnalysis.h \
		cmssw/ConstantsForHistoType.h \
		cmssw/ConstantsForKeyType.h \
		cmssw/ConstantsForLogger.h \
		cmssw/ConstantsForMonitorable.h \
		cmssw/ConstantsForPresentation.h \
		cmssw/ConstantsForRunType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/SiStripFedKey.o cmssw/SiStripFedKey.cc

.obj/moc_QConnectedTabWidget.o: .moc/moc_QConnectedTabWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_QConnectedTabWidget.o .moc/moc_QConnectedTabWidget.cpp

.obj/moc_CustomTQtWidget.o: .moc/moc_CustomTQtWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_CustomTQtWidget.o .moc/moc_CustomTQtWidget.cpp

.obj/moc_FedGraphicsView.o: .moc/moc_FedGraphicsView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_FedGraphicsView.o .moc/moc_FedGraphicsView.cpp

.obj/moc_FedGraphicsScene.o: .moc/moc_FedGraphicsScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_FedGraphicsScene.o .moc/moc_FedGraphicsScene.cpp

.obj/moc_TkView.o: .moc/moc_TkView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_TkView.o .moc/moc_TkView.cpp

.obj/moc_frmcommissioner.o: .moc/moc_frmcommissioner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmcommissioner.o .moc/moc_frmcommissioner.cpp

.obj/moc_frmstartup.o: .moc/moc_frmstartup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmstartup.o .moc/moc_frmstartup.cpp

.obj/moc_frmtreeviewer.o: .moc/moc_frmtreeviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmtreeviewer.o .moc/moc_frmtreeviewer.cpp

.obj/moc_frmreferencechooser.o: .moc/moc_frmreferencechooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmreferencechooser.o .moc/moc_frmreferencechooser.cpp

.obj/moc_frmruninfo.o: .moc/moc_frmruninfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmruninfo.o .moc/moc_frmruninfo.cpp

.obj/moc_frmdetails.o: .moc/moc_frmdetails.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmdetails.o .moc/moc_frmdetails.cpp

.obj/moc_frmdbtag.o: .moc/moc_frmdbtag.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmdbtag.o .moc/moc_frmdbtag.cpp

.obj/moc_frmtrends.o: .moc/moc_frmtrends.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmtrends.o .moc/moc_frmtrends.cpp

.obj/moc_frmsource.o: .moc/moc_frmsource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmsource.o .moc/moc_frmsource.cpp

.obj/moc_frmtkmap.o: .moc/moc_frmtkmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmtkmap.o .moc/moc_frmtkmap.cpp

.obj/moc_frmfedmap.o: .moc/moc_frmfedmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmfedmap.o .moc/moc_frmfedmap.cpp

.obj/moc_frmterminal.o: .moc/moc_frmterminal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frmterminal.o .moc/moc_frmterminal.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

